<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['uid','title','description','approved','image','publish_date','user_id'];

    protected $casts = [
        'publish_date' => 'date'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //inserting uid while creating New Post
        static::creating(function($post) {
            $uid = uniqid();
            while(self::where('uid',$uid)->count() > 0){
                $uid = uniqid();
            }
            $post->uid = $uid;
            $post->user_id = auth()->id();
        });
    }

    public function author() {
        return $this->belongsTo(User::class,'user_id');
    }

    public function approvedUser() {
        return $this->belongsTo(User::class)->where('is_admin',1)->orderBy('id');
    }

    public function scopePostStatus($query,$status) {
        return $query->where('approved',$status);
    }
}
